# Generated by Django 4.2.3 on 2023-07-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelInf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name1', models.CharField(blank=True, max_length=15)),
                ('char_name2', models.CharField(blank=True, max_length=15)),
                ('char_name3', models.CharField(blank=True, max_length=15)),
                ('char_age1', models.IntegerField(blank=True)),
                ('char_age2', models.IntegerField(blank=True)),
                ('char_age3', models.IntegerField(blank=True)),
                ('char_per1', models.CharField(blank=True, max_length=100)),
                ('char_per2', models.CharField(blank=True, max_length=100)),
                ('char_per3', models.CharField(blank=True, max_length=100)),
                ('char_sex1', models.CharField(blank=True, choices=[('남성', '남성'), ('여성', '여성'), ('등장시키지 않음', '등장시키지 않음')], max_length=8)),
                ('char_sex2', models.CharField(blank=True, choices=[('남성', '남성'), ('여성', '여성'), ('등장시키지 않음', '등장시키지 않음')], max_length=8)),
                ('char_sex3', models.CharField(blank=True, choices=[('남성', '남성'), ('여성', '여성'), ('등장시키지 않음', '등장시키지 않음')], max_length=8)),
                ('genre', models.CharField(blank=True, choices=[('로맨스', '로맨스'), ('판타지', '판타지'), ('고전', '고전'), ('공상과학', '공상과학'), ('일상', '일상'), ('공포', '공포')], max_length=10)),
                ('story', models.TextField(max_length=150)),
            ],
        ),
    ]
