# Generated by Django 4.2.3 on 2023-07-21 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_novelinf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.RemoveField(
            model_name='novelinf',
            name='char_age3',
        ),
        migrations.RemoveField(
            model_name='novelinf',
            name='char_name3',
        ),
        migrations.RemoveField(
            model_name='novelinf',
            name='char_per3',
        ),
        migrations.RemoveField(
            model_name='novelinf',
            name='char_sex3',
        ),
        migrations.AddField(
            model_name='novel',
            name='novel_infor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.novelinf'),
        ),
    ]
